### PR TITLE
Feature/my projects section

### PR DESCRIPTION
**Pull request by olevihon**

### CODE REVIEW

**Review by Sanetchek — CHANGES_REQUESTED** [review]
for now images don't load when I click on Load more btn, check it

**Comment by olevihon** [comment]
thank's i will check and fix this

**Comment by olevihon** [comment]
hi, fixes maked, please check

**Review by Sanetchek — CHANGES_REQUESTED** [review]
Change tag of Title to h3
Look on your styles font-family, sans-serif not needed

**Comment by olevihon** [comment]
done + update json file and function that render item ( add more fields in json )

**Review by Sanetchek — APPROVED** [review]

**Pull request merged**
